# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.CharField(max_length=150)),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
