FEATURE_ORDER = ['Overview',
                 'Show.Device',
                 'Show.Tenant',
                 'Show.EPG',
                 'Show.EP',
                 'Show.Contract',
                 'Show.L3_External',
                 'Show.Fault',
                 'Stats.Interface_Utilization',
                 'Stats.EPG_Utilization',
                 'Tool.Console',
                 'Setting']